name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testdb
          POSTGRES_PASSWORD: testdb
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testdb"
          --health-interval=1s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Install Go 1.24.5
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
          check-latest: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Run govulncheck
        run: make vulncheck

      - name: Check gofumpt formatting
        run: make fmtcheck

      - name: Run tests with coverage
        run: go test -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.out
